services:
  - type: web
    name: ai-signal
    env: docker
    region: singapore
    plan: starter
    branch: main
    dockerContext: ai/aisignal
    dockerfilePath: ai/aisignal/Dockerfile
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHON_VERSION
        value: 3.11.0
