services:
  - type: web
    name: ai-signal
    env: docker
    region: singapore
    plan: starter
    numInstances: 1
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHON_VERSION
        value: 3.11.0
